// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/get-market-snapshot.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^4.4.3";

// src/lib/mcp/market.ts
var SPOT = "https://api.binance.com";
var FUTURES = "https://fapi.binance.com";
function normalizeSymbol(input) {
  const s = input.trim().toUpperCase().replace(/[^A-Z0-9]/g, "");
  return /USDT$|USDC$|BTC$|ETH$/.test(s) ? s : `${s}USDT`;
}
function base(market) {
  return market === "futures" ? FUTURES : SPOT;
}
function path(market, endpoint) {
  return market === "futures" ? `/fapi/v1${endpoint}` : `/api/v3${endpoint}`;
}
async function getJson(url) {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`Binance request failed [${res.status}]: ${await res.text()}`);
  return res.json();
}
async function fetchTicker(symbol, market) {
  const [price, stats] = await Promise.all([
    getJson(`${base(market)}${path(market, "/ticker/price")}?symbol=${symbol}`),
    getJson(`${base(market)}${path(market, "/ticker/24hr")}?symbol=${symbol}`)
  ]);
  return {
    price: Number(price.price),
    changePercent24h: Number(stats.priceChangePercent),
    high24h: Number(stats.highPrice),
    low24h: Number(stats.lowPrice),
    quoteVolume24h: Number(stats.quoteVolume),
    fetchedAt: (/* @__PURE__ */ new Date()).toISOString()
  };
}
async function fetchCandles(symbol, interval, limit, market) {
  const raw = await getJson(
    `${base(market)}${path(market, "/klines")}?symbol=${symbol}&interval=${interval}&limit=${limit}`
  );
  return raw.map((k) => ({
    openTime: k[0],
    open: Number(k[1]),
    high: Number(k[2]),
    low: Number(k[3]),
    close: Number(k[4]),
    volume: Number(k[5])
  }));
}
function ema(values, period) {
  if (values.length < period) return null;
  const k = 2 / (period + 1);
  let acc = values.slice(0, period).reduce((a, b) => a + b, 0) / period;
  for (let i = period; i < values.length; i++) acc = values[i] * k + acc * (1 - k);
  return acc;
}
function rsi(values, period = 14) {
  if (values.length < period + 1) return null;
  let gain = 0;
  let loss = 0;
  for (let i = 1; i <= period; i++) {
    const d = values[i] - values[i - 1];
    if (d >= 0) gain += d;
    else loss -= d;
  }
  gain /= period;
  loss /= period;
  for (let i = period + 1; i < values.length; i++) {
    const d = values[i] - values[i - 1];
    gain = (gain * (period - 1) + Math.max(d, 0)) / period;
    loss = (loss * (period - 1) + Math.max(-d, 0)) / period;
  }
  if (loss === 0) return 100;
  return 100 - 100 / (1 + gain / loss);
}
function swingLevels(candles, lookback = 60) {
  const window = candles.slice(-lookback);
  const high = Math.max(...window.map((c) => c.high));
  const low = Math.min(...window.map((c) => c.low));
  return { swingHigh: high, swingLow: low, range: high - low };
}

// src/lib/mcp/tools/get-market-snapshot.ts
var get_market_snapshot_default = defineTool({
  name: "get_market_snapshot",
  title: "Get market snapshot",
  description: "Fetch a live Binance snapshot for a coin and timeframe: current price, 24h stats, EMA20/EMA50, RSI(14), swing high/low and the last candles. Works for spot and futures.",
  inputSchema: {
    symbol: z.string().min(2).describe("Coin or pair, e.g. BTC, BTCUSDT, SOLUSDT."),
    timeframe: z.string().default("1h").describe("Binance interval such as 15m, 1h, 4h, 1d."),
    market: z.enum(["spot", "futures"]).default("spot").describe("Binance market.")
  },
  annotations: { readOnlyHint: true, idempotentHint: false, openWorldHint: true },
  handler: async ({ symbol, timeframe, market }) => {
    const pair = normalizeSymbol(symbol);
    try {
      const [ticker, candles] = await Promise.all([
        fetchTicker(pair, market),
        fetchCandles(pair, timeframe, 500, market)
      ]);
      const closes = candles.map((c) => c.close);
      const snapshot = {
        symbol: pair,
        market,
        timeframe,
        ...ticker,
        ema20: ema(closes, 20),
        ema50: ema(closes, 50),
        ema200: ema(closes, 200),
        rsi14: rsi(closes, 14),
        ...swingLevels(candles),
        candleCount: candles.length,
        lastCandles: candles.slice(-5)
      };
      return {
        content: [{ type: "text", text: JSON.stringify(snapshot, null, 2) }],
        structuredContent: snapshot
      };
    } catch (error) {
      return {
        content: [{ type: "text", text: `Could not load market data for ${pair}: ${error.message}` }],
        isError: true
      };
    }
  }
});

// src/lib/mcp/tools/list-favorite-coins.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.95.3";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-favorite-coins.ts
var list_favorite_coins_default = defineTool2({
  name: "list_favorite_coins",
  title: "List favorite coins",
  description: "List the signed-in user's favorite coins saved in the scanner watchlist.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("favorite_coins").select("symbol, added_at").order("added_at", { ascending: false });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { favorites: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/add-favorite-coin.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^4.4.3";
var add_favorite_coin_default = defineTool3({
  name: "add_favorite_coin",
  title: "Add favorite coin",
  description: "Add a coin to the signed-in user's favorite coins watchlist.",
  inputSchema: {
    symbol: z2.string().min(2).describe("Coin or pair, e.g. SOL or SOLUSDT.")
  },
  annotations: { readOnlyHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ symbol }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const pair = normalizeSymbol(symbol);
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("favorite_coins").insert({ user_id: ctx.getUserId(), symbol: pair }).select("symbol, added_at");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Added ${pair} to favorites.` }],
      structuredContent: { favorite: data?.[0] ?? { symbol: pair } }
    };
  }
});

// src/lib/mcp/tools/remove-favorite-coin.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^4.4.3";
var remove_favorite_coin_default = defineTool4({
  name: "remove_favorite_coin",
  title: "Remove favorite coin",
  description: "Remove a coin from the signed-in user's favorite coins watchlist.",
  inputSchema: {
    symbol: z3.string().min(2).describe("Coin or pair to remove, e.g. SOLUSDT.")
  },
  annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ symbol }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const pair = normalizeSymbol(symbol);
    const supabase = supabaseForUser(ctx);
    const { error } = await supabase.from("favorite_coins").delete().eq("symbol", pair);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: `Removed ${pair} from favorites.` }] };
  }
});

// src/lib/mcp/tools/list-trades.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^4.4.3";
var list_trades_default = defineTool5({
  name: "list_trades",
  title: "List trades",
  description: "List the signed-in user's journaled trades, optionally filtered by status or symbol.",
  inputSchema: {
    status: z4.enum(["open", "closed", "all"]).default("all").describe("Filter by trade status."),
    symbol: z4.string().optional().describe("Optional exact pair filter, e.g. BTCUSDT."),
    limit: z4.number().int().min(1).max(100).default(25).describe("Maximum rows to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, symbol, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("trades").select(
      "id, symbol, side, status, quantity, entry_price, exit_price, stop_loss, take_profit, pnl, pnl_percent, opened_at, closed_at, notes, tags"
    ).order("opened_at", { ascending: false }).limit(limit);
    if (status !== "all") query = query.eq("status", status);
    if (symbol) query = query.eq("symbol", symbol.trim().toUpperCase());
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { trades: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/log-trade.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z5 } from "npm:zod@^4.4.3";
var log_trade_default = defineTool6({
  name: "log_trade",
  title: "Log a trade",
  description: "Record a new trade in the signed-in user's trade journal.",
  inputSchema: {
    symbol: z5.string().min(2).describe("Pair, e.g. BTCUSDT."),
    side: z5.enum(["long", "short"]).describe("Trade direction."),
    entry_price: z5.number().positive().describe("Entry price."),
    quantity: z5.number().positive().default(1).describe("Position size."),
    stop_loss: z5.number().positive().optional().describe("Stop loss price."),
    take_profit: z5.number().positive().optional().describe("Take profit price."),
    notes: z5.string().max(2e3).optional().describe("Trade rationale or notes.")
  },
  annotations: { readOnlyHint: false, idempotentHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("trades").insert({
      user_id: ctx.getUserId(),
      symbol: normalizeSymbol(input.symbol),
      side: input.side,
      entry_price: input.entry_price,
      quantity: input.quantity,
      stop_loss: input.stop_loss ?? null,
      take_profit: input.take_profit ?? null,
      notes: input.notes ?? null,
      status: "open"
    }).select("id, symbol, side, entry_price, quantity, status, opened_at");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data?.[0] ?? {}, null, 2) }],
      structuredContent: { trade: data?.[0] }
    };
  }
});

// src/lib/mcp/tools/list-saved-strategies.ts
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z6 } from "npm:zod@^4.4.3";
var list_saved_strategies_default = defineTool7({
  name: "list_saved_strategies",
  title: "List saved strategies",
  description: "List the signed-in user's saved scanner strategies with their conditions, timeframe and scan pool.",
  inputSchema: {
    limit: z6.number().int().min(1).max(50).default(20).describe("Maximum strategies to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("saved_strategies").select("id, name, description, timeframe, scan_pool, conditions, updated_at").order("updated_at", { ascending: false }).limit(limit);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { strategies: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "cijmscjovgmvjcpayfoq";
var mcp_default = defineMcp({
  name: "pro-new",
  title: "pro new",
  version: "0.1.0",
  instructions: "Trading tools for this app. Use get_market_snapshot for live Binance price, EMA/RSI and swing levels on any pair and timeframe. Use list_favorite_coins, add_favorite_coin and remove_favorite_coin to manage the user's watchlist, list_trades and log_trade for their trade journal, and list_saved_strategies to inspect their scanner strategies. All user data tools act as the signed-in user.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    get_market_snapshot_default,
    list_favorite_coins_default,
    add_favorite_coin_default,
    remove_favorite_coin_default,
    list_trades_default,
    log_trade_default,
    list_saved_strategies_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
